language: bash
sudo: required
cache: apt
dist: precise

before_script:
  - wget http://software-lab.de/picoLisp-16.6.tgz -O /tmp/picolisp.tgz
  - cd /tmp; tar -xf /tmp/picolisp.tgz
  - cd /tmp/picoLisp/src64 && make
  - export PATH=$PATH:/tmp/picoLisp
  - git clone https://github.com/unscramble/jidoteki-admin /tmp/jidoteki-admin
  - sudo pip install ansible==1.8.4
  - cd /tmp/jidoteki-admin && git checkout merge-scripts && make PREFIX_DIR=/tmp

script:
  - cd ${TRAVIS_BUILD_DIR} && make check
